In [2]:
import numpy as np

# Passo 1 — Array de peças vendidas

In [3]:
pecas_vendidas = np.array([150, 120, 90, 210, 300, 250, 180])

print(pecas_vendidas)

[150 120  90 210 300 250 180]


# Passo 2 — Faturamento

In [4]:
faturamento = pecas_vendidas * 50

print(faturamento)

[ 7500  6000  4500 10500 15000 12500  9000]


# Passo 3 — Dias com mais de 200 peças

In [5]:
mascara = pecas_vendidas > 200

print(mascara)
print(pecas_vendidas[mascara])

[False False False  True  True  True False]
[210 300 250]


# Nível 2 — Múltiplas Filiais
Criar a matriz

In [6]:
vendas = np.array([
    [200, 220, np.nan, 250],
    [150, 180, 160, 190],
    [300, 310, 290, 330]
])

print(vendas)

[[200. 220.  nan 250.]
 [150. 180. 160. 190.]
 [300. 310. 290. 330.]]


# Passo 2 — Total por loja

In [7]:
total_por_loja = np.nansum(vendas, axis=1)

print(total_por_loja)

[ 670.  680. 1230.]


# Passo 3 — Média diária geral ignorando

In [8]:
media_geral = np.nanmean(vendas)

print(media_geral)

234.54545454545453


# Passo 4 — Verificar se a meta foi atingida

In [9]:
resultado_meta = np.where(
    vendas >= 200,
    'Meta Atingida',
    'Abaixo'
)

print(resultado_meta)

[['Meta Atingida' 'Meta Atingida' 'Abaixo' 'Meta Atingida']
 ['Abaixo' 'Abaixo' 'Abaixo' 'Abaixo']
 ['Meta Atingida' 'Meta Atingida' 'Meta Atingida' 'Meta Atingida']]


# Nível 3 — Avançado
Passo 1 — Gerar 50 vendas aleatórias

In [10]:
rng = np.random.default_rng(42)

categorias = np.array(['Eletrônicos', 'Roupas', 'Casa'])

vendas_clientes = rng.choice(categorias, size=50)

print(vendas_clientes)

['Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas' 'Casa' 'Eletrônicos'
 'Casa' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Casa' 'Casa' 'Casa'
 'Casa' 'Roupas' 'Eletrônicos' 'Casa' 'Roupas' 'Roupas' 'Roupas'
 'Eletrônicos' 'Casa' 'Casa' 'Roupas' 'Roupas' 'Casa' 'Roupas' 'Roupas'
 'Roupas' 'Eletrônicos' 'Eletrônicos' 'Roupas' 'Casa' 'Eletrônicos' 'Casa'
 'Casa' 'Eletrônicos' 'Roupas' 'Eletrônicos' 'Casa' 'Casa' 'Roupas'
 'Eletrônicos' 'Casa' 'Roupas' 'Casa' 'Casa' 'Casa']


# Passo 2 — Contar vendas por departamento

In [11]:
departamentos, quantidades = np.unique(
    vendas_clientes,
    return_counts=True
)

print(departamentos)
print(quantidades)

['Casa' 'Eletrônicos' 'Roupas']
[21 12 17]


# Passo 3 — Encontrar a campanha com maior faturamento

In [12]:
faturamento_campanhas = np.array([12000, 45000, 23000, 89000, 31000])

indice_campea = np.argmax(faturamento_campanhas)

print(indice_campea)

3


# Atividade 2 — Organização e Transformação de Dados
Nível 1 — Básico

In [13]:
dias = np.arange(1, 31)

print(dias)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


# Passo 2 — Metas igualmente espaçadas

In [14]:
metas = np.linspace(20000, 30000, 5)

print(metas)

[20000. 22500. 25000. 27500. 30000.]


# Passo 3 — Converter estoque para inteiro

In [15]:
estoque = np.array([10.5, 20.1, 30.9])

estoque_inteiro = estoque.astype(int)

print(estoque_inteiro)

[10 20 30]


# Passo 4 — Últimos 5 dias em ordem inversa

In [16]:
ultimos_5 = dias[-5:][::-1]

print(ultimos_5)

[30 29 28 27 26]


# Nível 2 — Intermediário

In [17]:
visitas = np.array([
    1000, 1200, 1500,
    1800, 2000, 2200,
    2500, 2700, 3000,
    3200, 3500, 3800
])

visitas_trimestres = visitas.reshape(4, 3)

print(visitas_trimestres)

[[1000 1200 1500]
 [1800 2000 2200]
 [2500 2700 3000]
 [3200 3500 3800]]


# Passo 2 — vstack()

In [18]:
primeiro_semestre = np.array([
    [1000, 1200, 1500],
    [1800, 2000, 2200]
])

segundo_semestre = np.array([
    [2500, 2700, 3000],
    [3200, 3500, 3800]
])

ano_completo = np.vstack([
    primeiro_semestre,
    segundo_semestre
])

print(ano_completo)

[[1000 1200 1500]
 [1800 2000 2200]
 [2500 2700 3000]
 [3200 3500 3800]]


# Passo 3 — Copiar o primeiro trimestre

In [19]:
primeiro_trimestre = ano_completo[0].copy()

print(primeiro_trimestre)

[1000 1200 1500]


# Nível 3 — Avançado
Passo 1 — Ranking com argsort()

In [20]:
pontuacoes = np.array([85, 92, 78, 95, 88])

indices_ranking = np.argsort(pontuacoes)

print(indices_ranking)

[2 0 4 1 3]


# Passo 2 — np.newaxis e Broadcasting

In [21]:
precos = np.array([100, 200, 300, 400])

precos_coluna = precos[:, np.newaxis]

print(precos_coluna)

[[100]
 [200]
 [300]
 [400]]


# Passo 3 — Sistema de equações com np.linalg.solve()

In [22]:
A = np.array([
    [2, 1],
    [1, -1]
])

b = np.array([500, 100])

solucao = np.linalg.solve(A, b)

print("Custo da placa robótica: R$", solucao[0])
print("Custo do sensor: R$", solucao[1])

Custo da placa robótica: R$ 200.0
Custo do sensor: R$ 100.0
